;
; File generated by cc65 v 2.18 - Git dbba5f3
;
	.fopt		compiler,"cc65 v 2.18 - Git dbba5f3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_GD_Begin
	.export		_GD_Init
	.export		_GD_xhide
	.export		___start
	.export		___wstart
	.export		___end
	.export		_GD_wr
	.import		_spi_write_16
	.import		_spi_write
	.import		_spi_begin
	.import		_spi_end

; ---------------------------------------------------------------
; void __near__ GD_Begin (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GD_Begin: near

.segment	"CODE"

	jmp     _spi_begin

.endproc

; ---------------------------------------------------------------
; void __near__ GD_Init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GD_Init: near

.segment	"CODE"

	jsr     push0
	ldx     #$28
	lda     #$09
	jsr     pushax
	lda     #$01
	jsr     _GD_wr
	ldx     #$30
	lda     #$00
	jsr     ___wstart
	ldx     #$00
	txa
	jsr     stax0sp
L0002:	jsr     ldax0sp
	cmp     #$00
	txa
	sbc     #$02
	bvc     L0006
	eor     #$80
L0006:	bpl     L0003
	jsr     _GD_xhide
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L0002
L0003:	jsr     ___end
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ GD_xhide (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GD_xhide: near

.segment	"CODE"

	ldx     #$01
	lda     #$90
	jsr     _spi_write_16
	ldx     #$01
	lda     #$90
	jmp     _spi_write_16

.endproc

; ---------------------------------------------------------------
; void __near__ __start (unsigned int addr)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___start: near

.segment	"CODE"

	jsr     pushax
	jsr     _GD_Begin
	jsr     ldax0sp
	jsr     _spi_write_16
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ __wstart (unsigned int addr)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___wstart: near

.segment	"CODE"

	jsr     pushax
	jsr     ldax0sp
	pha
	txa
	ora     #$80
	tax
	pla
	jsr     ___start
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ __end (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	___end: near

.segment	"CODE"

	jmp     _spi_end

.endproc

; ---------------------------------------------------------------
; void __near__ GD_wr (unsigned int addr, char v)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GD_wr: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     ___wstart
	ldy     #$00
	lda     (sp),y
	jsr     _spi_write
	jsr     ___end
	jmp     incsp3

.endproc

