;
; File generated by cc65 v 2.18 - Git dbba5f3
;
	.fopt		compiler,"cc65 v 2.18 - Git dbba5f3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_acia_puts
	.import		_acia_getc
	.import		_GD_putchar
	.export		_i
	.export		_c
	.export		_main

.segment	"DATA"

_i:
	.word	$0000

.segment	"RODATA"

S0001:
	.byte	$61,$68,$6F,$6A,$20,$76,$6F,$6C,$6F,$76,$65,$00

.segment	"BSS"

_c:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp2
	ldx     #$00
	txa
	jsr     stax0sp
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _acia_puts
L0002:	jsr     _acia_getc
	sta     _c
	cmp     #$08
	beq     L0005
	inc     _i
	bne     L0008
	inc     _i+1
	jmp     L0008
L0005:	lda     _i
	cmp     #$01
	lda     _i+1
	sbc     #$00
	bvs     L0009
	eor     #$80
L0009:	bpl     L0008
	lda     _i
	sec
	sbc     #$01
	sta     _i
	bcs     L0008
	dec     _i+1
L0008:	lda     _i+1
	bne     L000B
	lda     _i
	cmp     #$32
	bne     L000B
	ldx     #$00
	txa
	sta     _i
	sta     _i+1
	lda     #$01
	jsr     addeq0sp
L000B:	lda     _i
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	lda     _c
	jsr     _GD_putchar
	jmp     L0002

.endproc

