;
; File generated by cc65 v 2.18 - Git dbba5f3
;
	.fopt		compiler,"cc65 v 2.18 - Git dbba5f3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_acia_putc
	.import		_acia_getc
	.import		_GD_Init
	.import		_GD_wr
	.import		_GD_putstr
	.export		_i
	.export		_c
	.export		_main

.segment	"DATA"

_i:
	.word	$0000

.segment	"RODATA"

S0001:
	.byte	$41,$68,$6F,$6A,$20,$56,$6F,$6C,$6F,$76,$65,$00

.segment	"BSS"

_c:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _GD_Init
	lda     #$00
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _GD_putstr
L0002:	jsr     _acia_getc
	sta     _c
	cmp     #$08
	beq     L0005
	inc     _i
	bne     L0008
	inc     _i+1
	jmp     L0008
L0005:	lda     _i
	ora     _i+1
	beq     L0008
	lda     _i
	sec
	sbc     #$01
	sta     _i
	bcs     L0008
	dec     _i+1
L0008:	lda     _i
	ldx     _i+1
	jsr     pushax
	lda     _c
	jsr     _GD_wr
	lda     _c
	jsr     _acia_putc
	jmp     L0002

.endproc

